### PR TITLE
Jleeothon

### PR DESCRIPTION
**Pull request by jleeothon**
[Review on Reviewable](https://reviewable.io/reviews/cortexlang/cortex/269)

### CODE REVIEW

**Comment by SanderMertens** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[packages/cortex/profiling/src/profiling.c, line 32 \[r2\]](https://reviewable.io:443/reviews/cortexlang/cortex/269#-JsMJiAleg3qSpKkpEHW)** ([raw file](https://github.com/cortexlang/cortex/blob/1797ce4314d9dfc3c1d982440a6944ab85d6c4fd/packages/cortex/profiling/src/profiling.c#L32)):</sup>
It is uncertain when this function will be called for the first time. It could be that it will be called from a different thread than the main thread, or worse, at the same time by multiple different threads. In that case, two threads could (temporarily) end up with two thread keys.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cortexlang/cortex/269)

**Comment by jleeothon** [comment]
<sup>**[packages/cortex/profiling/src/profiling.c, line 32 \[r2\]](https://reviewable.io:443/reviews/cortexlang/cortex/269#-JsMJiAleg3qSpKkpEHW)** ([raw file](https://github.com/cortexlang/cortex/blob/1797ce4314d9dfc3c1d982440a6944ab85d6c4fd/packages/cortex/profiling/src/profiling.c#L32)):</sup>
Let me correct that.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cortexlang/cortex/269)

**Comment by jleeothon** [comment]
<sup>**[packages/cortex/profiling/src/profiling.c, line 32 \[r2\]](https://reviewable.io:443/reviews/cortexlang/cortex/269#-JsMJiAleg3qSpKkpEHW)** ([raw file](https://github.com/cortexlang/cortex/blob/1797ce4314d9dfc3c1d982440a6944ab85d6c4fd/packages/cortex/profiling/src/profiling.c#L32)):</sup>
Can I assume that a module is only imported once? That is, that the load function will not run more that once?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cortexlang/cortex/269)

**Comment by SanderMertens** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[packages/cortex/profiling/src/profiling.c, line 32 \[r2\]](https://reviewable.io:443/reviews/cortexlang/cortex/269#-JsMJiAleg3qSpKkpEHW)** ([raw file](https://github.com/cortexlang/cortex/blob/1797ce4314d9dfc3c1d982440a6944ab85d6c4fd/packages/cortex/profiling/src/profiling.c#L32)):</sup>
Yes, the load won't run more than once. Even if the package is loaded multiple times, the core will notice that it is already loaded.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cortexlang/cortex/269)

**Comment by jleeothon** [comment]
<sup>**[packages/cortex/profiling/src/profiling.c, line 32 \[r2\]](https://reviewable.io:443/reviews/cortexlang/cortex/269#-JsMJiAleg3qSpKkpEHW)** ([raw file](https://github.com/cortexlang/cortex/blob/1797ce4314d9dfc3c1d982440a6944ab85d6c4fd/packages/cortex/profiling/src/profiling.c#L32)):</sup>
:confused: How could I share an object between different *.c implementation files? So, I would like to be able to use `struct profiling_TlsValue` and `profiling_key` from both `profiling.c` and `profiling__load.c`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cortexlang/cortex/269)

**Comment by jleeothon** [comment]
<sup>**[packages/cortex/profiling/src/profiling.c, line 32 \[r2\]](https://reviewable.io:443/reviews/cortexlang/cortex/269#-JsMJiAleg3qSpKkpEHW)** ([raw file](https://github.com/cortexlang/cortex/blob/1797ce4314d9dfc3c1d982440a6944ab85d6c4fd/packages/cortex/profiling/src/profiling.c#L32)):</sup>
I think I can use `extern` for the variable, but maybe not for the struct. Should I instead use an extra user header file?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cortexlang/cortex/269)

**Comment by SanderMertens** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[packages/cortex/profiling/src/profiling.c, line 23 \[r2\]](https://reviewable.io:443/reviews/cortexlang/cortex/269#-JsMJiAleg3qSpKkpEHW)** ([raw file](https://github.com/cortexlang/cortex/blob/1797ce4314d9dfc3c1d982440a6944ab85d6c4fd/packages/cortex/profiling/src/profiling.c#L23)):</sup>
extern is only for variables. I would put the struct in a private header file (one that is located in the 'src' directory).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cortexlang/cortex/269)

**Pull request merged**
